name: Pipeline

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main

jobs:
  install-test-build-push:
    runs-on: ubuntu-latest
    container: biomapas/cicd-full:0.0.2

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install
        run: |
          python --version
          node --version
          npm --version
          npm install -g aws-cdk
          python -m pip install . --upgrade
          python -m pip list
      - name: IntegrationTest
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}

          pytest b_cfn_s3_large_deployment_tests/integration/tests
      - name: Install
        run: python -m pip install wheel twine

      - name: Build
        run: |
          rm -rf b_cfn_s3_large_deployment_tests
          python setup.py sdist bdist_wheel

      - name: Upload
        run: python -m twine upload dist/* -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
